# Generated by Django 3.2.7 on 2025-12-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_id', models.CharField(max_length=150)),
                ('candidate_name', models.CharField(max_length=150)),
                ('party_name', models.CharField(max_length=150)),
                ('photo', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('seat', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='election_commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='election_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('id_proof', models.CharField(max_length=120)),
                ('status', models.CharField(default='pending', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='result_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.CharField(max_length=150)),
                ('seat_id', models.CharField(max_length=150)),
                ('candidate_id', models.CharField(max_length=150)),
                ('votes', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='seat_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('election_id', models.CharField(max_length=150)),
                ('seat_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='vote_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.CharField(max_length=150)),
                ('seat_id', models.CharField(max_length=150)),
                ('candidate_id', models.CharField(max_length=150)),
                ('voter_id', models.CharField(max_length=150)),
            ],
        ),
    ]
