# Generated by Django 3.2.7 on 2026-01-06 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=150)),
                ('party_name', models.CharField(max_length=150)),
                ('photo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='election_commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='election_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=150)),
                ('jurisdiction', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='legislature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('id_proof', models.CharField(max_length=120)),
                ('voter_id', models.CharField(max_length=150, unique=True)),
                ('status', models.CharField(default='pending', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='seat_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('election_id', models.CharField(max_length=150)),
                ('seat_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='voterlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_voting.constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_voting.election_tbl')),
                ('legislature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_voting.legislature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_voting.register')),
            ],
        ),
        migrations.CreateModel(
            name='vote_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_voting.candidate_tbl')),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_voting.constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_voting.election_tbl')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_voting.register')),
            ],
        ),
        migrations.CreateModel(
            name='result_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.TextField()),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_voting.constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_voting.election_tbl')),
            ],
        ),
        migrations.AddField(
            model_name='election_tbl',
            name='legislature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online_voting.legislature'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='legislature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_voting.legislature'),
        ),
        migrations.AddField(
            model_name='candidate_tbl',
            name='constituency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_voting.constituency'),
        ),
        migrations.AddField(
            model_name='candidate_tbl',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_voting.election_tbl'),
        ),
        migrations.AddField(
            model_name='candidate_tbl',
            name='legislature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_voting.legislature'),
        ),
    ]
